const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{test}=require('node:test'),{webcrypto}=require('node:crypto'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../src/background/index.js'),'utf8');
function setup(fetch){let data={ztServerToken:'KEY_A',ztServerTokenSavedAt:Date.now(),ztServerLicenseDetails:{license_status:'ACTIVE',daily_limit:100,entitlements:['export']}},listener;const clone=structuredClone,chrome={runtime:{id:'test',getURL:p=>'chrome-extension://test/'+p,onInstalled:{addListener(){}},onMessage:{addListener(fn){listener=fn;}}},storage:{local:{async setAccessLevel(){},async get(keys){return Object.fromEntries(keys.filter(k=>k in data).map(k=>[k,clone(data[k])]));},async set(v){Object.assign(data,clone(v));},async remove(keys){keys.forEach(k=>delete data[k]);}},session:{async setAccessLevel(){},async set(){},async remove(){}}},tabs:{async query(){return[];},async sendMessage(){}},cookies:{async get(){return null;}}};const ctx=vm.createContext({chrome,fetch,crypto:webcrypto,AbortSignal,console:{log(){},warn(){},error(){}},Date,Promise,JSON,Math,URL,setTimeout});vm.runInContext(source,ctx);return {run:s=>vm.runInContext(s,ctx),read:()=>clone(data),msg:(message,sender={id:'test',url:'chrome-extension://test/src/ui/action-popup.html'})=>new Promise(resolve=>listener(message,sender,resolve))};}
const valid=()=>({status:200,ok:true,json:async()=>({valid:true,license_status:'ACTIVE',entitlements:['export']})});
test('server denial clears ACTIVE authorization',async()=>{const a=setup(async()=>({status:403,ok:false,json:async()=>({valid:false,error:'LICENSE_SUSPENDED'})}));assert.equal((await a.run('ztServerLoginFlow("KEY_A",true)')).ok,false);assert.equal(a.read().ztServerLicenseDetails.license_status,'SUSPENDED');assert.equal((await a.run('publicSession()')).authed,false);});
test('late validation never restores key after logout',async()=>{let release;const a=setup(()=>new Promise(r=>release=r)),pending=a.run('ztServerLoginFlow("KEY_A",true)');await new Promise(r=>setImmediate(r));await a.run('ztServerLogoutFlow()');release(valid());await pending;assert.equal(a.read().ztServerToken,undefined);});
test('refresh cache follows current key',async()=>{const a=setup(async()=>valid());await a.run('ztServerRefreshMeFlow(false)');await a.run('ztServerLogoutFlow()');await a.run('ztServerLoginFlow("KEY_B",false)');assert.equal((await a.run('ztServerRefreshMeFlow(false)')).license,'KEY_B');});
test('old denial never alters a new key session',async()=>{let release,calls=0;const a=setup(()=>++calls===1?new Promise(r=>release=r):Promise.resolve(valid())),old=a.run('ztServerLoginFlow("KEY_A",true)');await new Promise(r=>setImmediate(r));await a.run('ztServerLoginFlow("KEY_B",false)');release({status:403,ok:false,json:async()=>({valid:false,error:'LICENSE_REVOKED'})});await old;assert.equal(a.read().ztServerToken,'KEY_B');assert.equal(a.read().ztServerLicenseDetails.license_status,'ACTIVE');});
test('offline keeps key and marks authorization stale',async()=>{const a=setup(async()=>{throw new Error('offline');});assert.equal((await a.run('ztServerLoginFlow("KEY_A",true)')).ok,false);assert.equal(a.read().ztServerToken,'KEY_A');assert.equal(a.read().ztServerLicenseDetails.license_status,'STALE');});
test('missing Facebook cookie is not ready',async()=>{assert.equal((await setup(async()=>valid()).run('ztGetFacebookAccountStatus()')).ready,false);});
test('content cannot read license or arbitrary storage; foreign sender is denied',async()=>{const a=setup(async()=>valid()),fb={id:'test',url:'https://www.facebook.com/groups/123'},s=await a.msg({action:'ZT_SERVER_SESSION_GET'},fb);assert.equal(s.authed,true);assert.equal(s.license,undefined);assert.equal((await a.msg({action:'CHROME_STORAGE_GET',key:'ztServerToken'},fb)).ok,false);assert.equal((await a.msg({action:'ZT_SERVER_LOGIN',licenseKey:'KEY_B'},fb)).ok,false);assert.equal((await a.msg({action:'ZT_SERVER_SESSION_GET'},{id:'evil',url:'https://evil.example'})).ok,false);});
test('Graph paging rejects outside host',async()=>{const urls=[],a=setup(async url=>{urls.push(url);return {ok:true,text:async()=> 'EAAB123456789'};});await assert.rejects(a.run('fanpageFetchPostsPage("12345","https://evil.example/token",0)'));assert.ok(!urls.includes('https://evil.example/token'));});
test('phone transport retry uses stable request ID and backend only',async()=>{let calls=0;const bodies=[],a=setup(async(url,options)=>{assert.ok(url.endsWith('/api/license/phones'));bodies.push(JSON.parse(options.body));if(++calls===1)throw new Error('lost');return {ok:true,status:200,json:async()=>({ok:true,phoneMap:{12345:'0901234567'},quota:{license_status:'ACTIVE',daily_limit:100,daily_used:1}})};});assert.equal((await a.run('getPhoneMap(["12345"])'))['12345'],'0901234567');assert.equal(bodies[0].requestId,bodies[1].requestId);});
test('CSV escapes spreadsheet formulas and quotes',()=>{const s=fs.readFileSync(path.join(__dirname,'../src/ui/modal.js'),'utf8'),m=s.match(/  function escapeCsvCell\(s\) \{[\s\S]*?\n  \}/),c=vm.createContext({});assert.ok(m);vm.runInContext(m[0],c);assert.equal(vm.runInContext('escapeCsvCell("=HYPERLINK(1)")',c),"'=HYPERLINK(1)");assert.equal(vm.runInContext('escapeCsvCell("a,b")',c),'"a,b"');});
